import { jsPDF } from "jspdf";

const COLORS = {
  LOW:      { r: 16,  g: 185, b: 129 }, // emerald-500
  MEDIUM:   { r: 245, g: 158, b: 11  }, // amber-500
  HIGH:     { r: 239, g: 68,  b: 68  }, // red-500
  CRITICAL: { r: 185, g: 28,  b: 28  }, // red-800
};

function riskColor(risk) {
  return COLORS[risk?.toUpperCase()] ?? { r: 100, g: 116, b: 139 }; // slate-500
}

function formatDate(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

function scoreBar(doc, x, y, score, barW = 110, barH = 6) {
  const pct = Math.min(Math.max(Math.round((score ?? 0) * 100), 0), 100);

  // Track (gray)
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(x, y, barW, barH, 2, 2, "F");

  // Fill
  const c =
    pct >= 75 ? { r: 239, g: 68,  b: 68  } :
    pct >= 45 ? { r: 245, g: 158, b: 11  } :
    pct >= 20 ? { r: 234, g: 179, b: 8   } :
                { r: 16,  g: 185, b: 129 };
  const fillW = Math.max((barW * pct) / 100, pct > 0 ? 4 : 0);
  doc.setFillColor(c.r, c.g, c.b);
  doc.roundedRect(x, y, fillW, barH, 2, 2, "F");

  return pct;
}

/**
 * Generates and downloads a plagiarism report PDF for the given project.
 * @param {object} project – populated Project document (from /api/projects/:id)
 */
export function downloadPlagiarismReportPDF(project) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const PW = doc.internal.pageSize.getWidth();   // 210
  const margin = 18;
  const contentW = PW - margin * 2;
  let y = 0;

  const report  = project.plagiarismReport ?? {};
  const risk    = (report.highest_risk ?? "UNKNOWN").toUpperCase();
  const rColor  = riskColor(risk);
  const pct     = Math.min(Math.max(Math.round((report.highest_score ?? 0) * 100), 0), 100);

  // ── Header band ──────────────────────────────────────────────────────────────
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 0, PW, 38, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("Plagiarism Analysis Report", margin, 17);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(199, 210, 254); // indigo-200
  doc.text("Generated by Review System  ·  " + formatDate(new Date().toISOString()), margin, 27);

  y = 50;

  // ── Project info block ───────────────────────────────────────────────────────
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(margin, y, contentW, 36, 3, 3, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, contentW, 36, 3, 3, "S");

  const col2 = margin + contentW / 2;
  const rowH = 9;

  const labelCell = (lx, ly, label, value) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(label.toUpperCase(), lx + 4, ly + 4.5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59); // slate-800
    const lines = doc.splitTextToSize(value || "—", contentW / 2 - 10);
    doc.text(lines[0], lx + 4, ly + 4.5 + 5.5);
  };

  labelCell(margin,  y + 2,  "Project", project.title ?? "—");
  labelCell(col2,    y + 2,  "Status",  (project.status ?? "—").toUpperCase());
  labelCell(margin,  y + 2 + rowH + 4,  "Mentor",  project.mentor?.name ?? "—");
  labelCell(col2,    y + 2 + rowH + 4,  "Students", project.students?.map(s => s.name).join(", ") || "—");

  y += 44;

  // ── Risk badge ───────────────────────────────────────────────────────────────
  const badgeW = 60;
  doc.setFillColor(rColor.r, rColor.g, rColor.b);
  doc.roundedRect(margin, y, badgeW, 14, 4, 4, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(`${risk} RISK`, margin + badgeW / 2, y + 9.2, { align: "center" });

  y += 22;

  // ── Section: Similarity Score ────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text("SIMILARITY SCORE", margin, y);
  y += 5;

  const barW = contentW - 30;
  scoreBar(doc, margin, y, report.highest_score, barW, 7);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(`${pct}%`, margin + barW + 4, y + 5.5);

  y += 16;

  // ── Stats grid (3 boxes) ─────────────────────────────────────────────────────
  const boxW  = (contentW - 8) / 3;
  const boxH  = 28;
  const stats = [
    { label: "Comparisons",   value: String(report.total_comparisons ?? "—") },
    { label: "Analysis Time", value: report.total_elapsed_seconds != null ? `${report.total_elapsed_seconds.toFixed(1)}s` : "—" },
    { label: "Checked On",    value: formatDate(report.checkedAt) },
  ];

  stats.forEach((s, i) => {
    const bx = margin + i * (boxW + 4);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(bx, y, boxW, boxH, 3, 3, "F");
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(bx, y, boxW, boxH, 3, 3, "S");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(s.label.toUpperCase(), bx + boxW / 2, y + 7, { align: "center" });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(i === 2 ? 8 : 15);
    doc.setTextColor(30, 41, 59);
    doc.text(s.value, bx + boxW / 2, y + 19, { align: "center" });
  });

  y += boxH + 12;

  // ── PDF Submission ───────────────────────────────────────────────────────────
  if (project.pdfFileName) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text("SUBMITTED FILE", margin, y);
    y += 5;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text(project.pdfFileName, margin, y);
    y += 10;
  }

  // ── Mentor review note ───────────────────────────────────────────────────────
  if (project.reviewNote) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text("MENTOR FEEDBACK", margin, y);
    y += 5;

    doc.setFillColor(255, 251, 235); // amber-50
    const noteLines = doc.splitTextToSize(`"${project.reviewNote}"`, contentW - 8);
    const noteH = noteLines.length * 5.5 + 8;
    doc.roundedRect(margin, y, contentW, noteH, 3, 3, "F");

    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(120, 53, 15); // amber-900
    doc.text(noteLines, margin + 4, y + 6.5);
    y += noteH + 8;
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  const PH = doc.internal.pageSize.getHeight();
  doc.setFillColor(241, 245, 249); // slate-100
  doc.rect(0, PH - 14, PW, 14, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Confidential — generated by the Review System", margin, PH - 5);
  doc.text(`Page 1`, PW - margin, PH - 5, { align: "right" });

  // ── Save ─────────────────────────────────────────────────────────────────────
  const safeName = (project.title ?? "Project")
    .replace(/[^a-zA-Z0-9\s_-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 80);

  doc.save(`${safeName}_Plagiarism_Report.pdf`);
}
